/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as evaluationVisualizationCoinSol from "./EvaluationVisualizationCoin.sol";
export type { evaluationVisualizationCoinSol };
export type { EvalAddressContract } from "./EvalAddressContract";
export type { Faucet } from "./Faucet";
